alias: windscreen-claim
description: Processes a workflow for a windscreen claim.
env:
- description: ""
  name: USER
  value: ""
- description: ""
  name: PASSWORD
  value: ""
name: Windscreen Claim Processor
prompt: You are a helpful and diligent Claims Processor, ONLY PROCESS THE CLAIM ID requested. Never change the Check IDs.
steps:
- step: get the claim from the tools available using the claim id, store in a workspace file called claim_{id}.md
- step: Use the Claims tool to update the claim internal_status field to Reviewing
- step: Get the Policy info from the tools available, store in a workspace file called claim_{id}_policy.md
- step: Download claim invoices from the API store to the workspace using BearerAuthDownloader tool.
- step: Convert the invoice PDFs in the workspace into PNG images.
- step: Extract all the relevant vendor, itemized costs, dates, and customer information, detailed car information from the invoice PNGs stored in the workspace.
- step: Store all invoice info into a file called claim_{id}_invoice_data.md in the workspace.
- step: Get all the checks, and do NOT change the IDs, for this claim id, and count the number of pending checks.
- while:
    condition: Are any checks still pending?
    maxLoops: 100
    steps:
    - step: Select the lowest id from the pending checks for this claim id.
    - step: Process the check with the lowest id for the claim id using the ValidationCheck tool.
    - step: Update the check with all of the details.
    - step: Get all the checks, and do NOT change the IDs, for this claim id, and count the number of pending checks.
- while:
- step: Get all checks for the claim id, do NOT change the check IDs.
- step: If ALL checks PASSED with no failures or pending, use the Claims tool to set the internal_status=Approved otherwise set internal_status=2nd review
- step: If the claim internal_status was set to approved, also use the Claims tool to set the claims status field to approved.
- step: if the claim was approved, summarize the review results and use the Claims tool to update the message field. Otherwise, use the Claims tool to set the message field to "Pending additional review"
tools:
- github.com/cloudnautique/agent-demo/obot/agent/tool.gpt
- github.com/obot-platform/tools/images
- github.com/obot-platform/tools/workspace-files
- github.com/cloudnautique/experimental-tools/pdf2png
- workspace-files
type: workflow
